# Generated by Django 4.1.7 on 2023-10-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_augmentapiin_augmentnodein_augmentperin_augmentrelin'),
    ]

    operations = [
        migrations.AddField(
            model_name='augmentperin',
            name='level',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
