# Generated by Django 4.1.7 on 2023-10-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_augmentperin_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='augmentapiin',
            name='level',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
