# Generated by Django 4.1.7 on 2023-10-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_augmentapiin_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apkName', models.CharField(max_length=100)),
                ('behaviors', models.CharField(blank=True, max_length=500)),
                ('chains', models.CharField(blank=True, max_length=500)),
                ('des', models.CharField(blank=True, max_length=1200)),
            ],
        ),
    ]
