# Generated by Django 4.1.7 on 2023-10-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_apkrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apkrecord',
            old_name='des',
            new_name='des1',
        ),
        migrations.AddField(
            model_name='apkrecord',
            name='des2',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name='apkrecord',
            name='des3',
            field=models.CharField(blank=True, max_length=1200),
        ),
    ]
