# Generated by Django 4.1.7 on 2023-10-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_rename_des_apkrecord_des1_apkrecord_des2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkrecord',
            name='graph',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
