# Generated by Django 4.1.7 on 2023-10-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_apkrecord_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='augmentapiin',
            name='des',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='augmentperin',
            name='des',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
