# Generated by Django 4.1.7 on 2023-10-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_augmentapiin_des_augmentperin_des'),
    ]

    operations = [
        migrations.RenameField(
            model_name='augmentapiin',
            old_name='level',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='augmentperin',
            old_name='level',
            new_name='mark',
        ),
    ]
