# Generated by Django 4.2.7 on 2023-11-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_rename_level_augmentapiin_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisdk',
            name='idList',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='apisim',
            name='idList',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
