# Generated by Django 4.2.4 on 2024-03-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_apisdk_idlist_apisim_idlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApkRecord',
        ),
        migrations.RemoveField(
            model_name='apisdk',
            name='idList',
        ),
        migrations.RemoveField(
            model_name='apisim',
            name='idList',
        ),
        migrations.RemoveField(
            model_name='augmentapiin',
            name='des',
        ),
        migrations.RemoveField(
            model_name='augmentapiin',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='augmentperin',
            name='des',
        ),
        migrations.RemoveField(
            model_name='augmentperin',
            name='mark',
        ),
        migrations.AddField(
            model_name='augmentnodein',
            name='constList',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
