# Generated by Django 4.2.4 on 2024-03-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0042_delete_apkrecord_remove_apisdk_idlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apkName', models.CharField(max_length=100)),
                ('behaviors', models.CharField(blank=True, max_length=500)),
                ('graph', models.CharField(blank=True, max_length=1000)),
                ('chains', models.CharField(blank=True, max_length=500)),
                ('des1', models.CharField(blank=True, max_length=1200)),
                ('des2', models.CharField(blank=True, max_length=1200)),
                ('des3', models.CharField(blank=True, max_length=1200)),
            ],
        ),
        migrations.RemoveField(
            model_name='augmentnodein',
            name='constList',
        ),
        migrations.AddField(
            model_name='apisdk',
            name='idList',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='apisim',
            name='idList',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='augmentapiin',
            name='des',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='augmentapiin',
            name='mark',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='augmentnodein',
            name='constStr',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='augmentnodein',
            name='independent',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='augmentperin',
            name='des',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='augmentperin',
            name='mark',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
