# Generated by Django 4.2.4 on 2024-03-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_apkrecord_remove_augmentnodein_constlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiID', models.IntegerField(blank=True, null=True)),
                ('apiName', models.CharField(max_length=200)),
                ('des', models.CharField(blank=True, max_length=200)),
                ('inLevel', models.CharField(blank=True, max_length=50)),
                ('outLevel', models.CharField(blank=True, max_length=50)),
                ('addList', models.CharField(blank=True, max_length=200)),
                ('repList', models.CharField(blank=True, max_length=200)),
                ('mark', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MalOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeID', models.IntegerField(blank=True, null=True)),
                ('actionName', models.CharField(max_length=120)),
                ('perList', models.CharField(blank=True, default='', max_length=120)),
                ('apiList', models.CharField(blank=True, default='', max_length=120)),
                ('constStr', models.CharField(blank=True, default='', max_length=120)),
                ('mark', models.CharField(blank=True, default='', max_length=50)),
                ('independent', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MalPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perID', models.IntegerField(blank=True, null=True)),
                ('perName', models.CharField(max_length=200)),
                ('des', models.CharField(blank=True, max_length=200)),
                ('inLevel', models.CharField(blank=True, max_length=50)),
                ('outLevel', models.CharField(blank=True, max_length=50)),
                ('mark', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MalRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceID', models.IntegerField()),
                ('sourceAct', models.CharField(blank=True, default='', max_length=200)),
                ('targetID', models.IntegerField()),
                ('targetAct', models.CharField(blank=True, default='', max_length=200)),
                ('relation', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
