# Generated by Django 4.2.4 on 2024-04-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0044_malapi_maloperation_malpermission_malrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitiveapi',
            name='version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
